FROM golang:1.24.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /shipping-service ./cmd/shipping/main.go

FROM alpine:latest

WORKDIR /

COPY --from=builder /shipping-service /shipping-service

EXPOSE 8053

CMD ["/shipping-service"]