FROM golang:1.24.1-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o /order-service ./cmd/order/main.go

FROM alpine:latest

WORKDIR /

COPY --from=builder /order-service /order-service

EXPOSE 8051

CMD ["/order-service"]